sudo: false
language: node_js
node_js:
  - 12 # use nodejs v12 LTS
cache: npm
before_install:
  - git config --global user.name "KemengHuang"
  - git config --global user.email "KMHuang@stu.ecnu.edu.cn"
  - npm install -g hexo-cli
install:
  - npm i
branches:
  only:
    - hexo # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$GH_TOKEN@github.com/KemengHuang/KemengHuang.github.io.git master